name: custom_log
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  termare_view:
    path: ../../termare-space/termare_view

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
